---
title: "Apresentação proposta- ME710"
author: "Henrique Capatto"
output: 
    beamer_presentation:
      theme: "AnnArbor"
      colortheme: "dove"
      fonttheme: "structurebold"
fontsize: 10pt
---
```{r echo=FALSE}
#mudando o separador decimal para resultados "printados"
options(OutDec= ",")
```

```{r, echo=FALSE}
#definindo opções padrões dos chunks
knitr::opts_chunk$set(fig.width=5, fig.height=3.25, fig.align='center', echo=FALSE, warning=FALSE, message=FALSE)
```


```{r pacotes,cache = FALSE,echo=FALSE, warning = FALSE,eval=TRUE,message = FALSE, error = FALSE}
#eval= FALSE faz com que o R ignore este chunk
#echo = FALSE não permite que o chunk apareça no pdf

#pacotes = c("tidyverse","reshape2","knitr","captioner","gdata","gridExtra","Matrix","plotrix","xtable")
#install.packages(pacotes)

packages= c("tidyverse","data.table","reshape2","captioner","gridExtra","xtable","ggpubr","MASS", "ggfortify")

#mostra quais pacotes foram carregados
invisible(lapply(packages, require, character.only = TRUE))

figs <- captioner(prefix="Figura")
tbls <- captioner(prefix="Tabela")

#instalacao de um pacote pra "printar" tabelas mais bonitinhas
#install.packages('printr',type = 'source',repos = c('http://yihui.name/xran', 'http://cran.rstudio.com'))

```

```{r dados, cache=TRUE, eval=TRUE}

#path_arq = glue::glue(getwd(),'wiki_prices_redux.csv')

dados = fread("/home/henrique/Documentos/Unicamp/ME710/wiki_prices_redux.csv", showProgress = FALSE)

CPRT =  dados %>% filter(ticker=="CPRT")

AAPL =  dados %>% filter(ticker=="AAPL")

CPRT$date = as.Date(CPRT$date)

g1 = ggplot(CPRT, aes(x = date, y=close)) + geom_line() + scale_x_date(date_labels = "%Y", date_breaks = "1 year") + xlab("") + ylab("Preço")+theme_bw()

AAPL$date = as.Date(AAPL$date)

g2 = ggplot(AAPL, aes(x = date, y=close)) + geom_line() + scale_x_date(date_labels = "%Y", date_breaks = "1 year") + xlab("") + ylab("Preço")+theme_bw()


```

## Índice

- Introdução 
- Objetivo
- Análise descritiva

## Introdução

- Motivação

- Construção de portfólios

## Objetivo 

- O objetivo do presente estudo é construir um portfólio de ações resistente
a variações extremas de mercado, como as ocorrentes em crises sistêmicas, por exemplo, e 
fornecer ao investidor uma otimização na alocação de pesos dentro do portfólio de ações.


